#!/bin/sh

echo "1. hello bash."
echo "2. this is second line"
echo "3. another line"
echo '4. trying ilne inside single cotes'


read -p "give me some amount:" amount

if (($amount -ld 100));
then 
  echo "Thankyou. you could have givem more. It was just for name"
elif (($amoun -ld 100 || $amount ))

